### ISSUE TITLE
如果再刷新控件上面有控件的话，会显示透明，然后看得见下面的刷新头部

### ISSUE THREAD

**Issue by Lxiaoqiang** [whichname/PTLRecyclerView#1]
我的界面是有个title一个view，然后下面还有一栏筛选控件，刷新控件放在下面，显示出来的效果是，直接透过了筛选控件，看到了刷新的头部，why?可能我没表达清楚，我微信xq2770602251

**Comment by whichname** [comment]
试试用FrameLayout把RecyclerView装起来（即用FrameLayout作为RecyclerView的父层）

**Comment by Lxiaoqiang** [comment]
ok，是行的，为什么？

**Comment by whichname** [comment]
因为采用margin为负数的方式隐藏头部。如果当前层级有别的元素的话，RecyclerView的头部就会遮住上面的元素。
