### ISSUE TITLE
调用方法设置没有更多数据，并没有显示getNoMoreView中返回的view，并且在下拉刷新的时候会短暂显示

### ISSUE THREAD

**Issue by Lxiaoqiang** [whichname/PTLRecyclerView#2]
setNoMore(true);在没有更多数据的时候，但是没起作用，footerView还是没有变，还是松手即刷新，箭头向下，但是并没有显示我在DefaultLoadFooterCreator中的getNoMoreView返回的视图

**Comment by whichname** [comment]
不好意思，最近比较忙，等我忙完手头的项目，会第一时间测试修复

**Comment by Lxiaoqiang** [comment]
ok，如果要不能复现，找我就行

**Comment by Lxiaoqiang** [comment]
多谢了

**Comment by whichname** [comment]
不好意思，时间有点久。
上拉加载的RecyclerView并没有提供setNoMore方法，自动加载的AutoLoadRecyclerView才有这个方法，AutoLoadRecyclerView的尾部构造器应该使用AutoLoadFooterCreator。
后续会考虑在上拉加载的RecyclerView中加入setNoMore方法。
