### ISSUE TITLE
直接引用引起内存泄漏

### ISSUE THREAD

**Issue by lvanli** [whichname/PTLRecyclerView#5]
DefaultAutoLoadFooterCreator类的ivAnim变量，在初始化的时候就调用了addUpdateListener。但是没有cancel。所以当对应activity销毁之后会出现内存泄漏。
而且因为初始化的时候就会创建一个DefaultAutoLoadFooterCreator，所以就算注册了新的Creator也会有一样的内存泄漏。

**Comment by whichname** [comment]
感谢指出，已提交!
不好意思，年底工作太忙，现在才有时间初略改一改。
为你的认真打call！！！
