### ISSUE TITLE
list数据为空，再次加载数据时，无法显示到最新数据

### ISSUE THREAD

**Issue by chairman987** [whichname/PTLRecyclerView#6]
list数据为空，再次加载数据时，无法显示到最新数据。
第一次加载数据，list个数为0，此时列表为空。
第二次加载数据时（更换查询条件），list中的个数大于0，此时列表不能及时刷新。
必须重新绑定Adapter对象。
经过跟踪，   
 public void completeLoad(int loadItemCount) {
        mIsLoading = false;
        setLoadingViewGone();

        int startItem = mRealAdapter.getItemCount() + mAdapter.getHeadersCount() - loadItemCount;
         这行的索引使用有BUG。
         请大神修改。
谢谢

**Comment by whichname** [comment]
@chairman987 
你好，感谢你的指出。
我按你说的尝试了一下，一开始mDatas是空的，第二次加载数据，使用了mDatas.addAll()方法添加数据，再调用了completeLoad(mDatas.size())，发现并无异常哦。
是否可以提供相关demo以重现呢？

**Comment by chairman987** [comment]
是我使用的问题，UI刷新出现了异常，我后来解决了，忘了来关闭了。
